name: FMC
main: flour.fmc.FMC
version: DEV
api-version: 1.15
description: FMC modular vanilla tweaks plugin
author: Flourick

commands:
    announce:
        description: Announces a completely custom message to everyone.
        aliases: [ann]
        permission: fmc.announce
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command> §7<§rmessage§7>§r"
    colorme:
        description: Colors your name!
        aliases: [cme]
        permission: fmc.colorme
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command> §7<§rcolor§7|§rlist§7>§r"
    wakeplayer:
        description: Wakes a player if he is trying to sleep to skip the night.
        aliases: [wp]
        permission: fmc.wakeplayer
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command> §7<§rplayer§7>"
    setbase:
        description: Places a marker with your name on DynMap.
        aliases: [sb]
        permission: fmc.dynfmc
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command>"
    removebase:
        description: Removes previously placed marker with your name on DynMap.
        aliases: [rmb]
        permission: fmc.dynfmc
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command>"
    statistics:
        description: Shows statistics for given player or yourself
        aliases: [stats]
        permission: fmc.stats
        permission-message: §cYou do not have permission for that!
        usage: "§eUsage:§r /<command> §7[§rplayer§7]"

permissions:
    fmc.announce:
        description: Allows the use of announce command
        default: op
    fmc.colorme:
        description: Allows the use of colorme command
        default: true
    fmc.wakeplayer:
        description: Allows the use of wakeplayer command
        default: true
    fmc.dynfmc:
        description: Allows the use of setbase and removebase command
        default: true
    fmc.stats:
        description: Allows the use of statistics command for yourself
        default: true
    fmc.stats.others:
        description: Allows the use of statistics command for yourself and others
        default: op
        children:
            fmc.stats: true
            