name: FMC
main: flour.fmc.FMC
version: DEV
api-version: 1.15
description: FMC utilities
author: Flourick

commands:
    colorme:
        description: Colors your name!
        aliases: [cme]
        permission: fmc.colorme
        permission-message: §cYou do not have permission to color yourself!
        usage: "§eUsage:§r /<command> §7<§rcolor§7|§rlist§7>§r"
        
permissions:
    fmc.colorme:
        description: Allows to color your name
        default: true
            